---
- name: Enable Calm
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/api/nutanix/v3/services/nucalm"
    method: POST
    body:
      state: DISABLE
    validate_certs: "{{ role_nutanix_pc_svc_calm_host_validate_certs }}"
    body_format: json
    status_code: 202
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
  register: nutanix_calm_disable

- name: Debug nutanix_calm_disable
  ansible.builtin.debug:
    var: nutanix_calm_disable
  when:
    - role_nutanix_pc_svc_calm_debug

- name: Wait for Calm enable task to complete
  ansible.builtin.import_role:
    name: grdavies.role_nutanix_prism_monitor_task
  vars:
    role_nutanix_prism_monitor_task_host: "{{ role_nutanix_pc_svc_calm_host }}"
    role_nutanix_prism_monitor_task_host_username: "{{ role_nutanix_pc_svc_calm_host_username }}"
    role_nutanix_prism_monitor_task_host_password: "{{ role_nutanix_pc_svc_calm_host_password }}"
    role_nutanix_prism_monitor_task_host_port: "{{ role_nutanix_pc_svc_calm_host_port | default(omit) }}"
    role_nutanix_prism_monitor_task_host_validate_certs: "{{ role_nutanix_pc_svc_calm_host_validate_certs | default(omit) }}"
    role_nutanix_prism_monitor_task_debug: "{{ role_nutanix_pc_svc_calm_debug | default(omit) }}"
    role_nutanix_prism_monitor_task_uuid: "{{ nutanix_calm_disable.json.task_uuid }}"
    role_nutanix_prism_monitor_task_retries: 60
    role_nutanix_prism_monitor_task_retry_delay: 15
