---
- name: Enable Calm
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_auth_string_b64 }}/api/nutanix/v3/services/nucalm"
    method: POST
    body:
      state: ENABLE
      enable_nutanix_apps: "{{ role_nutanix_pc_svc_calm_default_apps }}"
    validate_certs: "{{ role_nutanix_pc_svc_calm_validate_certs }}"
    body_format: json
    status_code: 202
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
  register: role_nutanix_pc_svc_calm_enable

- name: Debug role_nutanix_pc_svc_calm_enable
  ansible.builtin.debug:
    var: role_nutanix_pc_svc_calm_enable
  when:
    - role_nutanix_pc_svc_calm_debug

- name: Wait for Calm enable task to complete
  ansible.builtin.import_role:
    name: grdavies.role_nutanix_prism_monitor_task
  vars:
    role_nutanix_prism_monitor_task_host: "{{ role_nutanix_pc_svc_calm_host }}"
    role_nutanix_prism_monitor_task_username: "{{ role_nutanix_pc_svc_calm_username }}"
    role_nutanix_prism_monitor_task_password: "{{ role_nutanix_pc_svc_calm_password }}"
    role_nutanix_prism_monitor_task_port: "{{ role_nutanix_pc_svc_calm_port }}"
    role_nutanix_prism_monitor_task_validate_certs: "{{ role_nutanix_pc_svc_calm_validate_certs }}"
    role_nutanix_prism_monitor_task_debug: "{{ role_nutanix_pc_svc_calm_debug }}"
    role_nutanix_prism_monitor_task_uuid: "{{ role_nutanix_pc_svc_calm_enable.json.task_uuid }}"
    role_nutanix_prism_monitor_task_retries: 60
    role_nutanix_prism_monitor_task_retry_delay: 15
