---
- name: Get current Calm Enablement Status
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/api/nutanix/v3/services/nucalm/status"
    method: GET
    validate_certs: "{{ role_nutanix_pc_svc_calm_host_validate_certs }}"
    body_format: json
    status_code: 200
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
  register: nutanix_calm_state

- name: Debug nutanix_calm_state
  ansible.builtin.debug:
    var: nutanix_calm_state
  when:
    - role_nutanix_pc_svc_calm_debug

- name: Current status of Calm service(s)
  ansible.builtin.debug:
    msg: "Calm is currently in a '{{ nutanix_calm_state.json.service_enablement_status | lower }}' state."
