---
# tasks file for nutanix_role_prism_calm
- name: Setup connection to Nutanix API
  ansible.builtin.include_tasks: setup_api.yml

- name: "Task can only be run against Prism Central"
  ansible.builtin.fail:
    msg: "'nutanix_host' needs to be set to the IP or VIP of Prism Central. Please check the variable and try again."
  when:
    - nutanix_endpoint_prism_type != 'pc'

- name: Get Calm state
  ansible.builtin.include_tasks: get_state.yml

# - name: Check Calm Pre-Reqs
#   include_tasks: check_prereqs.yml
#   when:
#     - nutanix_calm_state.json.service_enablement_status != "ENABLED"
#     - nutanix_calm_enable | default(False)

- name: Enable Calm
  ansible.builtin.include_tasks: enable_service.yml
  when:
    - nutanix_calm_state.json.service_enablement_status != "ENABLED"
    - nutanix_calm_enable | default(False)

- name: Disable Calm
  ansible.builtin.include_tasks: disable_service.yml
  when:
    - nutanix_calm_state.json.service_enablement_status == "ENABLED"
    - nutanix_calm_enable | default(True)
