---
# tasks file for role_nutanix_pc_svc_calm
- name: Setup connection to Nutanix API
  ansible.builtin.include_role:
    name: grdavies.role_nutanix_prism_api
  vars:
    role_nutanix_prism_api_host: "{{ role_nutanix_pc_svc_calm_host }}"
    role_nutanix_prism_api_username: "{{ role_nutanix_pc_svc_calm_username }}"
    role_nutanix_prism_api_password: "{{ role_nutanix_pc_svc_calm_password }}"
    role_nutanix_prism_api_port: "{{ role_nutanix_pc_svc_calm_port }}"
    role_nutanix_prism_api_validate_certs: "{{ role_nutanix_pc_svc_calm_validate_certs }}"
    role_nutanix_prism_api_debug: "{{ role_nutanix_pc_svc_calm_debug }}"

- name: "Task can only be run against Prism Central"
  ansible.builtin.fail:
    msg: "'role_nutanix_pc_svc_calm_host' needs to be set to the IP or VIP of Prism Central. Please check the variable and try again."
  when:
    - role_nutanix_prism_api_endpoint_type != 'pc'

- name: Get Calm state
  ansible.builtin.include_tasks: get_state.yml

- name: Enable Calm
  ansible.builtin.include_tasks: enable_service.yml
  when:
    - nutanix_calm_state.json.service_enablement_status | lower != "enabled"
    - role_nutanix_pc_svc_calm_enable | default(false)
